# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HockeyMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=10)),
                ('marathon_link', models.CharField(max_length=100)),
                ('bet_link', models.CharField(max_length=100)),
                ('first_team', models.CharField(max_length=100)),
                ('second_team', models.CharField(max_length=100)),
                ('has_ended', models.BooleanField()),
            ],
        ),
    ]
