# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harbs', '0003_hockeyteam_standard_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hockeymatch',
            name='bet_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hockeymatch',
            name='has_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hockeymatch',
            name='marathon_link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
