# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('harbs', '0004_auto_20170121_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='hockeymatch',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
